### ISSUE TITLE
能否对于delaystage的复现给与一些指导意见

### ISSUE THREAD

**Issue by wcy666103** [kudofaye/Student-Guide#43]
你好，好兄弟，最近看了delaystage的那篇文章，试着跑了配套代码，但是里边有一些代码依赖前一篇文章iSpot中代码的日志分析，但是我读下来iSpot的代码没有找到相关功能，想问一下你有没有跑通代码或者说代码有没有更加配套的完整的（**比如说跑公共数据集时候的**），如果能提供（帮助）将不胜感激。

**Comment by kudofaye** [comment]
你好，你可以在delaystage的project中留言哈。关于公共数据集，你说的simulation吗？
具体问题也可以给[shaowujie@foxmail.com](mailto:shaowujie@foxmail.com)发邮件。谢谢！
